apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "networking.stakater.com/v1alpha1",
          "kind": "UptimeProbe",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "uptimeguardian"
            },
            "name": "uptimeprobe-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    createdAt: "2025-02-06T16:32:39Z"
    operators.operatorframework.io/builder: operator-sdk-v1.36.1
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: uptimeguardian.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: UptimeProbe is the Schema for the uptimeprobes API
      displayName: Uptime Probe
      kind: UptimeProbe
      name: uptimeprobes.networking.stakater.com
      version: v1alpha1
  description: Uptime management for Hypershift
  displayName: Uptime Guardian
  icon:
  - base64data: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA3OCA1OS44NDEiIGhlaWdodD0iNjIiPgogICAgPGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLTE2LjE3NiAtMTQuMjgpIj4KICAgICAgICA8cGF0aCBkPSJNMjAuOTMxIDE2Ljg4bDIwLjQ4Ni0uMDcxIDE2LjkyMiAzMy43MzUuMDA2IDEuNDQyLTE3LjIyLjA2LS4wMjUtNi4wOTUtMi45MjItMi4xNjctMTcuMTYxLjA2em0tMi4yNDgtMi40NjVsLjE0NSA0MS44MzggNDIuMDMzLS4xNDUtLjAyMS02LjUxNC0xNy41NDctMzUuMjYzeiIKICAgICAgICAgICAgICB0cmFuc2Zvcm09InRyYW5zbGF0ZSgxLjUyNyAuMDMxKSI+PC9wYXRoPgogICAgICAgIDxwYXRoCiAgICAgICAgICAgICAgICBmaWxsPSIjZmVjZDA3IgogICAgICAgICAgICAgICAgZD0iTTAgMEg0Mi4wMzRWMTEuMTQ3SDB6IgogICAgICAgICAgICAgICAgdHJhbnNmb3JtPSJyb3RhdGUoLS4xOTcgMTYzNzkuNTk0IC01ODkxLjY0MSkiCiAgICAgICAgPjwvcGF0aD4KICAgICAgICA8cGF0aAogICAgICAgICAgICAgICAgZD0iTTQ1LjY4NyAxNC4zbC4xODIgNTIuOTgzTDYwIDY3LjIzbDE0LjExNC00LjA1Mi0yNC4yNTQuMDgzLS4xNjgtNDguOTh6IgogICAgICAgICAgICAgICAgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMTcuOTcgLjAwMSkiCiAgICAgICAgPjwvcGF0aD4KICAgICAgICA8cGF0aAogICAgICAgICAgICAgICAgZD0iTTI0Ljk5NSA1Ni45MWE3LjcxMiA3LjcxMiAwIDExNy42ODYtNy43MzkgNy43MjEgNy43MjEgMCAwMS03LjY4NiA3LjczOSIKICAgICAgICAgICAgICAgIHRyYW5zZm9ybT0idHJhbnNsYXRlKC42NTggMTYuNTY1KSIKICAgICAgICA+PC9wYXRoPgogICAgICAgIDxwYXRoCiAgICAgICAgICAgICAgICBmaWxsPSIjZmZmIgogICAgICAgICAgICAgICAgZD0iTTI1LjE5IDQyLjM3OGE3LjA2NCA3LjA2NCAwIDExLTcuMDQxIDcuMDg5IDcuMDY1IDcuMDY1IDAgMDE3LjA0MS03LjA4OW0wLTEuM2E4LjM1OSA4LjM1OSAwIDEwOC4zODkgOC4zMzEgOC4zNjcgOC4zNjcgMCAwMC04LjM4OS04LjMzMSIKICAgICAgICAgICAgICAgIHRyYW5zZm9ybT0idHJhbnNsYXRlKC40MTMgMTYuMzIpIgogICAgICAgID48L3BhdGg+CiAgICAgICAgPHBhdGgKICAgICAgICAgICAgICAgIGQ9Ik00MS40MjMgNTYuODUyYTcuNzEyIDcuNzEyIDAgMTE3LjY4Ni03LjczNyA3LjcxOCA3LjcxOCAwIDAxLTcuNjg2IDcuNzM3IgogICAgICAgICAgICAgICAgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMTAuNjYyIDE2LjUzMSkiCiAgICAgICAgPjwvcGF0aD4KICAgICAgICA8cGF0aAogICAgICAgICAgICAgICAgZmlsbD0iI2ZmZiIKICAgICAgICAgICAgICAgIGQ9Ik00MS42MTggNDIuMzIxYTcuMDY1IDcuMDY1IDAgMTEtNy4wMzkgNy4wODkgNy4wNjcgNy4wNjcgMCAwMTcuMDM5LTcuMDg5bTAtMS4zQTguMzYgOC4zNiAwIDEwNTAgNDkuMzU3YTguMzcyIDguMzcyIDAgMDAtOC4zODktOC4zMzEiCiAgICAgICAgICAgICAgICB0cmFuc2Zvcm09InRyYW5zbGF0ZSgxMC40MTYgMTYuMjg2KSIKICAgICAgICA+PC9wYXRoPgogICAgICAgIDxwYXRoCiAgICAgICAgICAgICAgICBmaWxsPSIjZmZmIgogICAgICAgICAgICAgICAgZD0iTTM5LjU3OCA1MC4xOWEyLjg3OCAyLjg3OCAwIDExMi44NjktMi44OSAyLjg3OSAyLjg3OSAwIDAxLTIuODY5IDIuODg4IgogICAgICAgICAgICAgICAgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMTIuNDkxIDE4LjM2KSIKICAgICAgICA+PC9wYXRoPgogICAgICAgIDxwYXRoCiAgICAgICAgICAgICAgICBmaWxsPSIjZmZmIgogICAgICAgICAgICAgICAgZD0iTTM5LjY1MSA0NC43NjdhMi42MzYgMi42MzYgMCAxMS0yLjYyNyAyLjY0NSAyLjYzNSAyLjYzNSAwIDAxMi42MjctMi42NDVtMC0uNDg0YTMuMTIgMy4xMiAwIDEwMy4xMzEgMy4xMSAzLjEyMyAzLjEyMyAwIDAwLTMuMTMxLTMuMTEiCiAgICAgICAgICAgICAgICB0cmFuc2Zvcm09InRyYW5zbGF0ZSgxMi4zOTkgMTguMjY5KSIKICAgICAgICA+PC9wYXRoPgogICAgICAgIDxwYXRoCiAgICAgICAgICAgICAgICBmaWxsPSIjZmZmIgogICAgICAgICAgICAgICAgZD0iTTIzLjE4NSA1MC4yNDZhMi44NzggMi44NzggMCAxMTIuODY5LTIuODg4IDIuODggMi44OCAwIDAxLTIuODY5IDIuODg4IgogICAgICAgICAgICAgICAgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMi41MDkgMTguMzk0KSIKICAgICAgICA+PC9wYXRoPgogICAgICAgIDxwYXRoCiAgICAgICAgICAgICAgICBmaWxsPSIjZmZmIgogICAgICAgICAgICAgICAgZD0iTTIzLjI1OSA0NC44MjNhMi42MzYgMi42MzYgMCAxMS0yLjYyOSAyLjY0NSAyLjYzOCAyLjYzOCAwIDAxMi42MjktMi42NDVtMC0uNDg0YTMuMTIgMy4xMiAwIDEwMy4xMzEgMy4xMSAzLjEyMyAzLjEyMyAwIDAwLTMuMTMxLTMuMTEiCiAgICAgICAgICAgICAgICB0cmFuc2Zvcm09InRyYW5zbGF0ZSgyLjQxOCAxOC4zMDMpIgogICAgICAgID48L3BhdGg+CiAgICAgICAgPHBhdGgKICAgICAgICAgICAgICAgIGQ9Ik0xNi4xNzYgMzguNDEyYTMuOTY0IDMuOTY0IDAgMTEzLjk3NyAzLjk1MSAzLjk2MyAzLjk2MyAwIDAxLTMuOTc3LTMuOTUxIgogICAgICAgICAgICAgICAgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMCAxMi4yNzIpIgogICAgICAgID48L3BhdGg+CiAgICAgICAgPHBhdGgKICAgICAgICAgICAgICAgIGZpbGw9IiNmZWNkMDciCiAgICAgICAgICAgICAgICBkPSJNMjMuNTg1IDM2Ljg2NmwtMS41NzctMTMuNDE4IDEuODI2LS4wMDZMMjYuMSAzMy4wOWw4LjAwOC41LjAxMSAzLjIzN3oiCiAgICAgICAgICAgICAgICB0cmFuc2Zvcm09InRyYW5zbGF0ZSgzLjU1MSA1LjU3OCkiCiAgICAgICAgPjwvcGF0aD4KICAgICAgICA8cGF0aAogICAgICAgICAgICAgICAgZmlsbD0iI2RlYjMwNiIKICAgICAgICAgICAgICAgIGQ9Ik0yMi4wMzIgNDEuMDgzYzUuMzI3LS4wMTkgMTAuMjIxIDIuMjMyIDExLjIxOSA5Ljk2OWwtMi45ODkuMDExYy44MDYtNi41NzYtMy40NjEtOS42NTItOC4yMy05Ljk4IgogICAgICAgICAgICAgICAgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoMy41NjYgMTYuMzIpIgogICAgICAgID48L3BhdGg+CiAgICAgICAgPHBhdGgKICAgICAgICAgICAgICAgIGZpbGw9IiNkZWIzMDYiCiAgICAgICAgICAgICAgICBkPSJNNDIuNjgxIDQxLjAyNmMtNS4zMjkuMDE5LTEwLjIwNSAyLjMtMTEuMTUxIDEwLjA0OGwyLjk4OS0uMDExYy0uODUxLTYuNTY4IDMuNC05LjY3NCA4LjE2Mi0xMC4wMzYiCiAgICAgICAgICAgICAgICB0cmFuc2Zvcm09InRyYW5zbGF0ZSg5LjM0OSAxNi4yODYpIgogICAgICAgID48L3BhdGg+CiAgICAgICAgPHBhdGgKICAgICAgICAgICAgICAgIGZpbGw9IiMzMzMiCiAgICAgICAgICAgICAgICBkPSJNMTguNzU2IDM1LjUyOWwxNy45NDQtLjA2MSAxLjA5My43NTMuMDI0IDYuODU3IDIwLjQ4Ni0yLjIzOS0xNy4yMTYuMDYxLS4wMjEtNi4xLTIuOTIyLTIuMTY4LTE5LjQuMDY3eiIKICAgICAgICAgICAgICAgIHRyYW5zZm9ybT0idHJhbnNsYXRlKDEuNTY1IDExLjE3OCkiCiAgICAgICAgPjwvcGF0aD4KICAgICAgICA8cGF0aAogICAgICAgICAgICAgICAgZmlsbD0iI2ZmZiIKICAgICAgICAgICAgICAgIGQ9Ik00MC4yNTYgNDIuNjY3QTYuNzk0IDYuNzk0IDAgMDE0MyA1MS4zMzZhOS4yNzQgOS4yNzQgMCAwMC0yLjc0Ni04LjY2OSIKICAgICAgICAgICAgICAgIHRyYW5zZm9ybT0idHJhbnNsYXRlKDE0LjY2MyAxNy4yODUpIgogICAgICAgID48L3BhdGg+CiAgICAgICAgPHBhdGgKICAgICAgICAgICAgICAgIGZpbGw9IiNmZmYiCiAgICAgICAgICAgICAgICBkPSJNMjMuNzEzIDQyLjcyNGE2Ljc4OSA2Ljc4OSAwIDAxMi43NDYgOC42NjcgOS4yNzEgOS4yNzEgMCAwMC0yLjc0Ni04LjY2NyIKICAgICAgICAgICAgICAgIHRyYW5zZm9ybT0idHJhbnNsYXRlKDQuNTg5IDE3LjMyKSIKICAgICAgICA+PC9wYXRoPgogICAgICAgIDxwYXRoCiAgICAgICAgICAgICAgICBmaWxsPSIjZmZmIgogICAgICAgICAgICAgICAgZD0iTTIzLjMyMyAzNC45bDEwLjAxNi0uMDM0LjgxNy41ODEuMDIyIDYuMjcyLS45MzUtNS41ODYtLjM5MS0uNDY3eiIKICAgICAgICAgICAgICAgIHRyYW5zZm9ybT0idHJhbnNsYXRlKDQuMzUyIDEyLjUzNikiCiAgICAgICAgPjwvcGF0aD4KICAgICAgICA8cGF0aAogICAgICAgICAgICAgICAgZmlsbD0iI2JmOWEwNSIKICAgICAgICAgICAgICAgIGQ9Ik0yMi43NTEgMjMuNDQ0bDEuOTA5IDExLjYzNSA5LS42NTR2LS44MzNsLTguMDA4LS41LTIuMjctOS42NDh6IgogICAgICAgICAgICAgICAgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoNC4wMDQgNS41NzkpIgogICAgICAgID48L3BhdGg+CiAgICAgICAgPHBhdGgKICAgICAgICAgICAgICAgIGZpbGw9IiM5NTc1NTIiCiAgICAgICAgICAgICAgICBkPSJNNTEuMzEyIDM2LjFsLS4xMzMtLjEyNnoiCiAgICAgICAgICAgICAgICB0cmFuc2Zvcm09InRyYW5zbGF0ZSgyMS4zMTMgMTMuMjA3KSIKICAgICAgICA+PC9wYXRoPgogICAgICAgIDxwYXRoCiAgICAgICAgICAgICAgICBmaWxsPSIjOTU3NTUyIgogICAgICAgICAgICAgICAgZD0iTTUxLjAwNyAyNC45MjJsLS4xMTYtLjEwOHoiCiAgICAgICAgICAgICAgICB0cmFuc2Zvcm09InRyYW5zbGF0ZSgyMS4xMzkgNi40MTIpIgogICAgICAgID48L3BhdGg+CiAgICAgICAgPHBhdGgKICAgICAgICAgICAgICAgIGZpbGw9IiNjNjljNmQiCiAgICAgICAgICAgICAgICBkPSJNMCAwSDE4LjIxMVYxOC4yMTFIMHoiCiAgICAgICAgICAgICAgICB0cmFuc2Zvcm09InJvdGF0ZSgtLjE5NyAxMjc5Mi41MzcgLTIwMjEyLjQ3NCkiCiAgICAgICAgPjwvcGF0aD4KICAgICAgICA8cGF0aAogICAgICAgICAgICAgICAgZmlsbD0iIzk1NzU1MiIKICAgICAgICAgICAgICAgIGQ9Ik0wIDBIMy45MTJWMy45NTVIMHoiCiAgICAgICAgICAgICAgICB0cmFuc2Zvcm09InJvdGF0ZSgtLjE5NyAxMjc4OC44NCAtMjIyOTEuNzEpIgogICAgICAgID48L3BhdGg+CiAgICAgICAgPHBhdGgKICAgICAgICAgICAgICAgIGZpbGw9IiM5NTc1NTIiCiAgICAgICAgICAgICAgICBkPSJNMCAwSDMuOTEyVjMuOTU2SDB6IgogICAgICAgICAgICAgICAgdHJhbnNmb3JtPSJyb3RhdGUoLS4xOTcgMTY5MzQuODA2IC0yMjI5OC44MzQpIgogICAgICAgID48L3BhdGg+CiAgICAgICAgPHBhdGgKICAgICAgICAgICAgICAgIGZpbGw9IiNjNjljNmQiCiAgICAgICAgICAgICAgICBkPSJNMCAwSDE1LjcwOFYxNS43MDhIMHoiCiAgICAgICAgICAgICAgICB0cmFuc2Zvcm09InJvdGF0ZSgtLjE5NyA3NzgzLjA1OCAtMjAyMDMuOTI2KSIKICAgICAgICA+PC9wYXRoPgogICAgICAgIDxwYXRoCiAgICAgICAgICAgICAgICBmaWxsPSIjOTU3NTUyIgogICAgICAgICAgICAgICAgZD0iTTAgMEgzLjM3NVYzLjQxM0gweiIKICAgICAgICAgICAgICAgIHRyYW5zZm9ybT0icm90YXRlKC0uMTk3IDc3NzkuNzQyIC0yMTk5Ni45NzMpIgogICAgICAgID48L3BhdGg+CiAgICAgICAgPHBhdGgKICAgICAgICAgICAgICAgIGZpbGw9IiM5NTc1NTIiCiAgICAgICAgICAgICAgICBkPSJNMCAwSDMuMzc1VjMuNDEzSDB6IgogICAgICAgICAgICAgICAgdHJhbnNmb3JtPSJyb3RhdGUoLS4xOTcgMTEzNTUuNjU2IC0yMjAwMy4zMzIpIgogICAgICAgID48L3BhdGg+CiAgICAgICAgPHBhdGgKICAgICAgICAgICAgICAgIGZpbGw9IiNjNjljNmQiCiAgICAgICAgICAgICAgICBkPSJNMCAwSDEwLjI4N1YxMC4yODZIMHoiCiAgICAgICAgICAgICAgICB0cmFuc2Zvcm09InJvdGF0ZSgtLjE5NyA0MTk4LjQxOCAtMjAxOTcuNTgzKSIKICAgICAgICA+PC9wYXRoPgogICAgICAgIDxwYXRoCiAgICAgICAgICAgICAgICBmaWxsPSIjOTU3NTUyIgogICAgICAgICAgICAgICAgZD0iTTAgMEgyLjIxVjIuMjM0SDB6IgogICAgICAgICAgICAgICAgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoNzMuNTI2IDE0LjU2NSkiCiAgICAgICAgPjwvcGF0aD4KICAgICAgICA8cGF0aAogICAgICAgICAgICAgICAgZmlsbD0iIzk1NzU1MiIKICAgICAgICAgICAgICAgIGQ9Ik0wIDBIMi4yMVYyLjIzNEgweiIKICAgICAgICAgICAgICAgIHRyYW5zZm9ybT0icm90YXRlKC0uMTk3IDY1MzguMjMzIC0yMTM3Ni40MTUpIgogICAgICAgID48L3BhdGg+CiAgICA8L2c+Cjwvc3ZnPg==
    mediatype: image/svg+xml
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - hypershift.openshift.io
          resources:
          - hostedclusters
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - networking.stakater.com
          resources:
          - uptimeprobes
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - networking.stakater.com
          resources:
          - uptimeprobes/finalizers
          verbs:
          - update
        - apiGroups:
          - networking.stakater.com
          resources:
          - uptimeprobes/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: uptimeguardian-controller-manager
      deployments:
      - label:
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: uptimeguardian
          control-plane: controller-manager
        name: uptimeguardian-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.16.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: ghcr.io/stakater/uptimeguardian:v0.0.1
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: uptimeguardian-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: uptimeguardian-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - Uptime Guardian Operator
  - Hypershift
  - Openshift
  - Red Hat
  - Stakater
  - Route
  - Probe
  links:
  - name: Uptimeguardian
    url: https://uptimeguardian.domain
  maturity: alpha
  provider:
    name: Stakater AB
    url: https://www.stakater.com
  version: 0.0.1
