name: "Setup Docker"
description: "Setup Docker repository"
inputs:
  TAG:
    description: Git action Tag
    required: true

  CONTAINER_REGISTRY_URL:
    description: "Registry URL to publish image"
    required: true

  CONTAINER_REGISTRY_USERNAME:
    description: "Registry username to login"
    required: true

  CONTAINER_REGISTRY_PASSWORD:
    description: "Registry password to login"
    required: true

outputs:
  IMAGE_REPOSITORY:
    description: "The tag for the workflow run"
    value: ${{ steps.repository.outputs.IMAGE_REPOSITORY }}
runs:
  using: "composite"
  steps:
    - name: Verify container registry secrets
      shell: bash
      run: |
        if [ "${{ inputs.CONTAINER_REGISTRY_URL }}" == "" ] || [ "${{ inputs.CONTAINER_REGISTRY_USERNAME }}" == "" ] || [ "${{ inputs.CONTAINER_REGISTRY_PASSWORD }}" == "" ]; then
          echo "Required secrets 'CONTAINER_REGISTRY_URL' or 'CONTAINER_REGISTRY_USERNAME' or 'CONTAINER_REGISTRY_PASSWORD' are not set!"
          exit 1
        fi

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: image=moby/buildkit:v0.9.3
        buildkitd-flags: --debug

    - name: Login to Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.CONTAINER_REGISTRY_URL }}
        username: ${{ inputs.CONTAINER_REGISTRY_USERNAME }}
        password: ${{ inputs.CONTAINER_REGISTRY_PASSWORD }}

    - name: Generate image repository path
      id: repository
      shell: bash
      run: |
        echo IMAGE_REPOSITORY=$(echo ${{ inputs.CONTAINER_REGISTRY_URL }}/${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]') | tee -a $GITHUB_OUTPUT $GITHUB_ENV
