---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - networking.stakater.com
  resources:
  - uptimeprobes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.stakater.com
  resources:
  - uptimeprobes/finalizers
  verbs:
  - update
- apiGroups:
  - networking.stakater.com
  resources:
  - uptimeprobes/status
  verbs:
  - get
  - patch
  - update
