# permissions for end users to view uptimeprobes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: uptimeguardian
    app.kubernetes.io/managed-by: kustomize
  name: uptimeprobe-viewer-role
rules:
- apiGroups:
  - networking.stakater.com
  resources:
  - uptimeprobes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.stakater.com
  resources:
  - uptimeprobes/status
  verbs:
  - get
