name: "Bundle"
description: "Build & push Operator bundle"
inputs:
  GOLANG_VERSION:
    description: Go version to use
    default: "~1.18"
    required: false
    type: string
outputs:
  lint_status:
    description: 'The result of the linting step'
runs:
  using: "composite"
  steps:

