name: "Generate Tag"
description: "Setup Docker"
inputs:
  PR:
    description: Go version to use
    default: "false"
    required: false

  RELEASE_BRANCH:
    description: Release branch to push changes
    required: false
    default: main
outputs:
  TAG:
    description: "The tag for the workflow run"
    value: ${{ steps.tag.outputs.TAG }}
runs:
  using: "composite"
  steps:
    - name: Generate Tag
      id: generate
      if: ${{ inputs.PR == 'false' }}
      uses: anothrNick/github-tag-action@1.71.0
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        WITH_V: false
        DEFAULT_BUMP: patch
        RELEASE_BRANCHES: ${{ inputs.RELEASE_BRANCH }}
        DRY_RUN: true

    - name: Set Tag
      if: ${{ inputs.PR == 'false' }}
      shell: bash
      run: echo "TAG=${{ steps.generate.outputs.new_tag }}" >> $GITHUB_ENV

    - name: Set Tag
      if: ${{ inputs.PR == 'true' }}
      shell: bash
      run: |
        sha=${{ github.event.pull_request.head.sha }}
        tag="SNAPSHOT-PR-${{ github.event.pull_request.number }}-${sha:0:8}"
        echo "TAG=$(echo ${tag})" >> $GITHUB_ENV

    - name: Output Tag
      id: tag
      shell: bash
      run: |
        echo "TAG=$(echo ${{ env.TAG }})" >> $GITHUB_OUTPUT