name: "Generate Tag"
description: "Setup Docker"
inputs:
  RELEASE_BRANCH:
    description: Release branch to push changes
    required: false
    default: main
outputs:
  TAG:
    description: "The tag for the workflow run"
    value: ${{ steps.tag.outputs.TAG }}

  PR_TAG:
    description: "The PR tag for the workflow run"
    value: ${{ steps.tag.outputs.PR_TAG }}
runs:
  using: "composite"
  steps:
    - name: Generate Tag
      id: generate
      uses: anothrNick/github-tag-action@1.71.0
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        WITH_V: false
        DEFAULT_BUMP: patch
        RELEASE_BRANCHES: ${{ inputs.RELEASE_BRANCH }}
        DRY_RUN: true

    - name: Set Tag
      shell: bash
      run: echo "TAG=${{ steps.generate.outputs.new_tag }}" >> $GITHUB_ENV

    - name: Set Tag
      id: tag
      shell: bash
      run: |
        sha=${{ github.event.pull_request.head.sha }}
        tag="-SNAPSHOT-PR-${{ github.event.pull_request.number }}-${sha:0:8}"
        echo "TAG=${{ steps.generate.outputs.new_tag }}" >> $GITHUB_OUTPUT
        echo "PR_TAG=$(echo ${tag})" >> $GITHUB_OUTPUT
