name: "Verify"
description: "Verify code"
inputs:
  GO_VERSION:
    description: Go version to use
    default: "~1.23"
    required: false

  ENABLE_LINTING:
    description: Run golangci-lint
    default: "true"
    required: false

  ENABLE_UNIT_TESTS:
    description: Run golang tests
    default: "true"
    required: false
runs:
  using: "composite"
  steps:
    - name: Set up Go
      id: go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.GO_VERSION }}

    - name: Run lint
      if: ${{ inputs.ENABLE_LINTING == 'true' }}
      shell: bash
      run: make lint

    - name: Run Tests
      if: ${{ inputs.ENABLE_UNIT_TESTS == 'true' }}
      shell: bash
      run: make test
