name: "Verify"
description: "Verify code"
inputs:
  GO_VERSION:
    description: Go version to use
    default: "~1.18"
    required: false

  ENABLE_LINTING:
    description: Run golangci-lint
    default: true
    required: false

  LINT_VERSION:
    description: golang-ci-lint version to use
    default: "v1.53.3"
    required: false

  ENABLE_UNIT_TESTS:
    description: Run golang tests
    default: true
    required: false
runs:
  using: "composite"
  steps:
    - name: Set up Go
      id: go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ inputs.GO_VERSION }}
        cache: true

    - name: Run Lint
      if: ${{ inputs.ENABLE_LINTING }}
      uses: golangci/golangci-lint-action@v6
      with:
        version: ${{ inputs.LINT_VERSION }}
        only-new-issues: false
        args: --timeout 10m

    - name: Run Tests
      if: ${{ inputs.ENABLE_UNIT_TESTS }}
      shell: bash
      run: make test
