name: Operator PR Request

on:
  workflow_call:
    inputs:
      GOLANG_VERSION:
        description: Go version to use
        default: "~1.18"
        required: false
        type: string

      Run_GOLANG_CI_LINT:
        description: Run golangci-lint
        default: true
        required: false
        type: boolean

      GOLANG_CI_LINT_VERSION:
        description: golang-ci-lint version to use
        default: "v1.53.3"
        required: false
        type: string

      RUN_GOLANG_TESTS:
        description: Run golang tests
        default: true
        required: false
        type: boolean

      DOCKERFILE_PATH:
        description: Dockerfile path
        required: true
        default: Dockerfile
        type: string

      OPERATOR_SDK_VERSION:
        description: Operator SDK version to use
        default: "v1.32.0"
        required: false
        type: string

      OPM_VERSION:
        description: OPM CLI version to use
        default: "v1.50.0"
        required: false
        type: string

    secrets:
      SLACK_WEBHOOK_URL:
        description: "Secret to send success/failure message to slack"
        required: true

      CONTAINER_REGISTRY_URL:
        description: "Registry URL to publish image"
        required: true

      CONTAINER_REGISTRY_USERNAME:
        description: "Registry username to login"
        required: true

      CONTAINER_REGISTRY_PASSWORD:
        description: "Registry password to login"
        required: true

jobs:
  make-operator-pull-request:
    name: Operator Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Go Checkout Build Lint Action with Env
        id: verify
        uses: ./.github/actions/composites/verify.yaml
        with:
          GOLANG_VERSION: ${{ inputs.GOLANG_VERSION }}
          RUN_GOLANG_CI_LINT: ${{ inputs.RUN_GOLANG_CI_LINT }}
          GOLANG_CI_LINT_VERSION: ${{ inputs.GOLANG_CI_LINT_VERSION }}
          RUN_GOLANG_TESTS: ${{ inputs.RUN_GOLANG_TESTS }}
          RELEASE_BRANCH: ${{ inputs.RELEASE_BRANCH }}

      - name: Setup Tag
        id: tag
        uses: ./.github/actions/tag.yaml
        with:
          PR: true

      - name: Setup Docker
        id: docker
        uses: ./.github/actions/docker.yaml
        with:
          TAG: ${{ steps.tag.outputs.TAG }}

      - name: Build & Push Bundle
        id: bundle
        uses: ./.github/actions/tag.yaml
        with:
          TAG: ${{ steps.tag.outputs.TAG }}

      - name: Build and Push Catalog
        run: make catalog-render catalog-build catalog-push
        env:
          PR_TAG: -${{ steps.tag.outputs.TAG }}

      - name: Comment on PR
        uses: mshick/add-pr-comment@v2
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          message-success: '@${{ github.actor }} Image is available for testing. `docker pull ${{ steps.docker.IMAGE_REPOSITORY }}:${{ steps.tag.outputs.TAG }}`'
          message-failure: '@${{ github.actor }} Yikes! You better fix it before anyone else finds out! [Build](https://github.com/${{ github.repository }}/commit/${{ github.event.pull_request.head.sha }}/checks) has Failed!'
          allow-repeats: true

      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        if: always() # Pick up events even if the job fails or is canceled.
        with:
          status: ${{ job.status }}
          fields: repo,author,action,eventName,ref,workflow
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
